// Code generated by pw build --target=cloudflare-workers. DO NOT EDIT.
//
// The fetch entry of a Popcorn Web Worker. The Wasm module is compiled once
// per isolate by the bundler import below; the Go program inside it is
// instantiated and run once per request, because github.com/syumai/workers
// registers its request handler from main and the host gives each fetch its
// own env and execution context. That is why the framework's startup summary
// is off under this target: it would be one line per request.
import "./wasm_exec.js";
import { connect } from "cloudflare:sockets";
import mod from "./app.wasm";

// tryCatch is called from the Go side to run a JavaScript function and hand
// back either its result or the exception it threw, because a thrown value
// cannot cross the syscall/js boundary as a Go error on its own.
globalThis.tryCatch = (fn) => {
  try {
    return { result: fn() };
  } catch (e) {
    return { error: e };
  }
};

// stringVars is the part of the Worker env a Go program can read as its
// environment: wrangler vars and secrets are strings, and bindings such as KV
// namespaces are objects the Go side reaches through the context instead.
function stringVars(env) {
  const vars = {};
  for (const [name, value] of Object.entries(env ?? {})) {
    if (typeof value === "string") {
      vars[name] = value;
    }
  }
  return vars;
}

async function run(context) {
  const go = new Go();
  // The host Go loader writes go.env into the module's environment; the
  // TinyGo loader ignores it and the generated entry reads the context
  // instead, so both compilers see the same variables.
  go.env = stringVars(context.env);
  let ready;
  const readyPromise = new Promise((resolve) => {
    ready = resolve;
  });
  const instance = new WebAssembly.Instance(mod, {
    ...go.importObject,
    workers: {
      ready: () => {
        ready();
      },
    },
  });
  // run resolves when the Go program exits. Before ready that is a startup
  // failure — the application's main called log.Fatal, say — and racing the
  // two turns it into a response with the reason instead of a request the
  // host kills as hung after the program has already said what went wrong.
  const exited = go.run(instance, context).then(() => {
    throw new Error("popcornweb: the Go program exited during startup before serving; the reason is in the log above");
  });
  await Promise.race([readyPromise, exited]);
}

export default {
  async fetch(request, env, ctx) {
    const binding = {};
    await run({ env, ctx, connect, binding });
    return binding.handleRequest(request);
  },
};
