// Code generated by tinybind HTML templates; DO NOT EDIT.

package pages

import (
	"github.com/shibukawa/tinybind-go/htmlbind"
	"github.com/shibukawa/tinybind-go/htmlbind/delta"
)

type LayoutParams struct {
	Children htmlbind.Fragment
}

var planLayoutOps = htmlbind.Builder[LayoutParams]{}

// planLayoutInput canonically encodes the declared inputs of Layout.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planLayoutInput(p LayoutParams) string {
	return delta.CanonJoin()
}

var planLayoutBoundary = &htmlbind.Boundary[LayoutParams]{
	ComponentID: "pages.layout.Layout",
	Attr:        "data-tb-id",
	Input:       planLayoutInput,
}

var planLayoutPlan = &htmlbind.Plan[LayoutParams]{
	Head:     nil,
	Boundary: planLayoutBoundary,
	Slots: func(p LayoutParams) []htmlbind.Fragment {
		return []htmlbind.Fragment{p.Children}
	},
	Ops: []htmlbind.Op[LayoutParams]{
		planLayoutOps.Static(" <main"),
		planLayoutOps.BoundaryAttr(),
		planLayoutOps.Static(" class=\"app\">"),
		planLayoutOps.Slot(func(p LayoutParams) htmlbind.Fragment { return p.Children },
			nil),
		planLayoutOps.Static("</main> "),
	},
}

// Layout binds Layout to its parameters, producing a renderable fragment.
func Layout(params LayoutParams) htmlbind.Fragment { return planLayoutPlan.Bind(params) }

// BindLayout binds Layout as a chain wrapper filling its unnamed slot.
func BindLayout(params LayoutParams) htmlbind.Wrapper {
	return planLayoutPlan.BindWrapper(params, func(target *LayoutParams, children htmlbind.Fragment) { target.Children = children })
}
