// Code generated by Popcorn Web via TinyBind; DO NOT EDIT.

package pages

import (
	"context"
	"github.com/shibukawa/popcornweb/pwruntime"
	"github.com/shibukawa/tinybind-go/htmlbind"
	"github.com/shibukawa/tinybind-go/htmlbind/delta"
	"github.com/shibukawa/tinybind-go/htmlupdate"
	"net/url"
)

type PageParams struct{}

type CardParams struct {
	Id   string
	Page int
}

var planPageOps = htmlbind.Builder[PageParams]{}

var planPagePlan = &htmlbind.Plan[PageParams]{
	Head: nil,
	Ops: []htmlbind.Op[PageParams]{
		planPageOps.Static(" <h1>home</h1> "),
		planPageOps.Component(func(p PageParams) htmlbind.Fragment { return Card(CardParams{Id: "card-1", Page: 1}) }),
		planPageOps.Static(" "),
	},
}

// Page binds Page to its parameters, producing a renderable fragment.
func Page(params PageParams) htmlbind.Fragment { return planPagePlan.Bind(params) }

var planCardOps = htmlbind.Builder[CardParams]{}

// planCardInput canonically encodes the declared inputs of Card.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planCardInput(p CardParams) string {
	return delta.CanonJoin(
		delta.CanonString[string](p.Id),
		delta.CanonInt(p.Page),
	)
}

var planCardBoundary = &htmlbind.Boundary[CardParams]{
	ComponentID: "pages.page.Card",
	Attr:        "data-tb-id",
	Instance:    func(p CardParams) string { return p.Id },
	Input:       planCardInput,
}

// CardReloadable publishes Card as a redraw endpoint.
// Its parameters arrive from the caller, so it authorizes them itself.
const CardKind = "pages.page.Card"

var CardReloadable = htmlupdate.Reloadable{
	KindID: CardKind,
	Render: func(_ context.Context, instanceID string, values url.Values) (htmlbind.Fragment, error) {
		var params CardParams
		params.Id = instanceID
		if err := htmlupdate.QueryInt(values, "page", &params.Page); err != nil {
			return htmlbind.Fragment{}, err
		}
		return Card(params), nil
	},
}

var planCardPlan = &htmlbind.Plan[CardParams]{
	Head:     nil,
	Boundary: planCardBoundary,
	Ops: []htmlbind.Op[CardParams]{
		planCardOps.Static(" <article"),
		planCardOps.BoundaryAttr(),
		planCardOps.Attr("id", func(p CardParams) (string, bool) { return htmlbind.Escape(p.Id), true }),
		planCardOps.Attr("data-tb-kind", func(CardParams) (string, bool) { return CardKind, true }),
		planCardOps.Static(">card page "),
		planCardOps.Raw(func(p CardParams) string { return htmlbind.FormatInt(p.Page) }),
		planCardOps.Static("</article> "),
	},
}

// Card binds Card to its parameters, producing a renderable fragment.
func Card(params CardParams) htmlbind.Fragment { return planCardPlan.Bind(params) }

// PwReloadables is every reloadable component Card can render, itself included
// when it is one. It is what Redraw reads, so a handler names the page and
// never a list that could fall out of step with the markup.
func (CardParams) PwReloadables() []htmlupdate.Reloadable {
	return []htmlupdate.Reloadable{CardReloadable}
}

// PwReloadables is every reloadable component Page can render, itself included
// when it is one. It is what Redraw reads, so a handler names the page and
// never a list that could fall out of step with the markup.
func (PageParams) PwReloadables() []htmlupdate.Reloadable {
	return []htmlupdate.Reloadable{CardReloadable}
}

func init() {
	_ = pwruntime.RegisterReloadable(CardReloadable)
}
