package pwcli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The shape tinybind emits: an internal builder carrying the statement name and
// its parameters, and a callable builder whose spelling follows from whether
// the statement was exported.
const generatedQueries = `// Code generated by tinybind templates; DO NOT EDIT.

package queries

import (
	"context"
	_tinybindsql "github.com/shibukawa/tinybind-go/sqlbind"
)

func _tinybindBuildFindExample(b *_tinybindsql.Builder, id int) error { return nil }

func BuildFindExample(id int) (_tinybindsql.Statement, error) { return _tinybindsql.Statement{}, nil }

func _tinybindBuildsearchExample(b *_tinybindsql.Builder, name string, limit int) error { return nil }

func buildSearchExample(name string, limit int) (_tinybindsql.Statement, error) {
	return _tinybindsql.Statement{}, nil
}

func _tinybindBuildoddParams(b *_tinybindsql.Builder, when map[string]int) error { return nil }

func buildOddParams(when map[string]int) (_tinybindsql.Statement, error) {
	return _tinybindsql.Statement{}, nil
}

func FindExample(ctx context.Context, id int) (int, error) { return 0, nil }
`

func scanQueries(t *testing.T) map[string]declaredQuery {
	t.Helper()
	directory := t.TempDir()
	path := filepath.Join(directory, "users_pw_gen.go")
	if err := os.WriteFile(path, []byte(generatedQueries), 0o644); err != nil {
		t.Fatal(err)
	}
	queries, err := scanDeclaredQueries(directory, plannedSources{})
	if err != nil {
		t.Fatal(err)
	}
	found := map[string]declaredQuery{}
	for _, query := range queries {
		found[query.Name] = query
	}
	return found
}

func TestScanFindsDeclaredStatementsAndTheirParameters(t *testing.T) {
	found := scanQueries(t)
	exported, ok := found["FindExample"]
	if !ok {
		t.Fatalf("queries = %v, want the exported statement", found)
	}
	if exported.Builder != "BuildFindExample" || !exported.exported() {
		t.Errorf("FindExample = %+v, want the exported builder", exported)
	}
	if len(exported.Params) != 1 || exported.Params[0].Name != "id" || exported.Params[0].Kind != "int" {
		t.Errorf("params = %+v, want one int named id", exported.Params)
	}
}

// An unexported statement is the one nothing outside the package can call, so
// it is the one the pane most needs to reach.
func TestScanReachesUnexportedStatements(t *testing.T) {
	found := scanQueries(t)
	unexported, ok := found["searchExample"]
	if !ok {
		t.Fatalf("queries = %v, want the unexported statement", found)
	}
	if unexported.exported() {
		t.Error("searchExample was treated as exported")
	}
	// Generation capitalises what it appends, so the callable builder is not
	// simply the statement name with a prefix.
	if unexported.Builder != "buildSearchExample" {
		t.Errorf("builder = %q, want buildSearchExample", unexported.Builder)
	}
	if len(unexported.Params) != 2 {
		t.Errorf("params = %+v, want two", unexported.Params)
	}
}

// A statement is listed even when a form cannot produce its arguments, so a
// developer scanning for it finds it and reads why rather than concluding that
// generation missed it.
func TestUnsupportedParameterTypesAreListedButNotRunnable(t *testing.T) {
	found := scanQueries(t)
	odd, ok := found["oddParams"]
	if !ok {
		t.Fatalf("queries = %v, want the statement with an unsupported parameter", found)
	}
	if odd.supported() {
		t.Errorf("oddParams = %+v, want it reported as unsupported", odd)
	}
	generated, err := queryRegistration([]declaredQuery{odd})
	if err != nil {
		t.Fatal(err)
	}
	source := string(generated)
	if !strings.Contains(source, "ErrUnsupportedParams") {
		t.Errorf("registration should report why it cannot run:\n%s", source)
	}
	if strings.Contains(source, "buildOddParams(") {
		t.Error("an unrunnable statement still generated a call to its builder")
	}
}

func TestRegistrationConvertsEachArgumentAndNamesIt(t *testing.T) {
	generated, err := queryRegistration([]declaredQuery{scanQueries(t)["searchExample"]})
	if err != nil {
		t.Fatal(err)
	}
	source := string(generated)
	if !strings.HasPrefix(source, "//go:build pwdev\n") {
		t.Error("the registration is not constrained to the development build mode")
	}
	if !strings.Contains(source, "package queries") {
		t.Error("the registration is not generated into the statement's own package")
	}
	for _, want := range []string{
		`pwdata.ArgString("name", args[0])`,
		`pwdata.ArgInt("limit", args[1])`,
		"return buildSearchExample(arg0, arg1)",
	} {
		if !strings.Contains(source, want) {
			t.Errorf("registration is missing %q:\n%s", want, source)
		}
	}
}

// The naming rule is checked rather than trusted: a statement whose callable
// builder is absent generates nothing, instead of a call that does not compile.
func TestAStatementWithNoCallableBuilderIsSkipped(t *testing.T) {
	directory := t.TempDir()
	source := `package queries

import _tinybindsql "github.com/shibukawa/tinybind-go/sqlbind"

func _tinybindBuildGhost(b *_tinybindsql.Builder, id int) error { return nil }
`
	if err := os.WriteFile(filepath.Join(directory, "ghost_pw_gen.go"), []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
	queries, err := scanDeclaredQueries(directory, plannedSources{})
	if err != nil {
		t.Fatal(err)
	}
	if len(queries) != 0 {
		t.Errorf("queries = %+v, want none when the builder is absent", queries)
	}
}

func TestCallableBuilderFollowsTheExportRule(t *testing.T) {
	for statement, want := range map[string]string{
		"FindExample":   "BuildFindExample",
		"searchExample": "buildSearchExample",
		"x":             "buildX",
	} {
		if got := callableBuilder(statement); got != want {
			t.Errorf("callableBuilder(%q) = %q, want %q", statement, got, want)
		}
	}
}

// queriesProject lays out a module with one queries package holding one
// generated file and the registration an earlier run wrote for it, linked into
// the main package the way planQueryLink leaves it.
func queriesProject(t *testing.T) (string, projectConfig) {
	t.Helper()
	root := t.TempDir()
	write := func(relative, content string) {
		t.Helper()
		path := filepath.Join(root, filepath.FromSlash(relative))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("go.mod", "module memoapp\n\ngo 1.27\n")
	write("cmd/memoapp/main.go", "package main\n\nfunc main() {}\n")
	write("cmd/memoapp/"+queryLinkFileName, "//go:build pwdev\n\npackage main\n\nimport _ \"memoapp/queries\"\n")
	write("queries/users.pw.sql", "package queries\n")
	write("queries/users_pw_gen.go", generatedQueries)
	write("queries/"+queryRegistryFileName, "//go:build pwdev\n\npackage queries\n")
	var config projectConfig
	config.Main = "./cmd/memoapp"
	config.Generate.Queries = []string{"queries"}
	return root, config
}

// The registration is compiled only under pwdev, so one that outlives its
// statements breaks pw dev and nothing else: it names builders that are gone,
// and go build never reads the file. It is the storybook registration's
// defect, in the step that was written beside it.
func TestQueryRegistrationIsRemovedWithItsLastStatement(t *testing.T) {
	for name, remove := range map[string]func(t *testing.T, root string){
		// The source is gone, and the generated file with it once this run
		// applies what it planned.
		"the last .pw.sql was deleted": func(t *testing.T, root string) {
			if err := os.Remove(filepath.Join(root, "queries", "users.pw.sql")); err != nil {
				t.Fatal(err)
			}
		},
		// The source stays and declares nothing any more, which is the shape
		// the scaffold's commented starter has.
		"the last statement was deleted": func(t *testing.T, root string) {},
	} {
		t.Run(name, func(t *testing.T) {
			root, config := queriesProject(t)
			remove(t, root)
			generated := filepath.Join(root, "queries", "users_pw_gen.go")
			// The template step has already planned the generated file's
			// removal, and the file is still on disk while this step runs.
			changes, err := planQueryRegistry(root, config, []fileChange{{path: generated, remove: true}})
			if err != nil {
				t.Fatal(err)
			}
			removed := removals(changes)
			if !removed[filepath.Join(root, "queries", queryRegistryFileName)] {
				t.Errorf("the registration of a package with no statement left was kept: %+v", changes)
			}
			if !removed[filepath.Join(root, "cmd", "memoapp", queryLinkFileName)] {
				t.Errorf("the link to a package that registers nothing was kept: %+v", changes)
			}
		})
	}
}

// A statement file deleted from a package that keeps another must leave the
// registration in the same run: the generated file it was read from is still on
// disk when the registration is planned, and a registration naming its builders
// would not compile until the run after.
func TestQueryRegistrationForgetsAFilePlannedForRemoval(t *testing.T) {
	root, config := queriesProject(t)
	queries := filepath.Join(root, "queries")
	const kept = `package queries

import _tinybindsql "github.com/shibukawa/tinybind-go/sqlbind"

func _tinybindBuildKeptOne(b *_tinybindsql.Builder, id int) error { return nil }

func BuildKeptOne(id int) (_tinybindsql.Statement, error) { return _tinybindsql.Statement{}, nil }
`
	if err := os.WriteFile(filepath.Join(queries, "kept.pw.sql"), []byte("package queries\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(queries, "kept_pw_gen.go"), []byte(kept), 0o644); err != nil {
		t.Fatal(err)
	}
	pending := []fileChange{{path: filepath.Join(queries, "users_pw_gen.go"), remove: true}}
	changes, err := planQueryRegistry(root, config, pending)
	if err != nil {
		t.Fatal(err)
	}
	for _, change := range changes {
		if change.path != filepath.Join(queries, queryRegistryFileName) {
			continue
		}
		source := string(change.source)
		if !strings.Contains(source, "BuildKeptOne") || strings.Contains(source, "BuildFindExample") {
			t.Fatalf("the registration names a builder whose generated file is being removed:\n%s", source)
		}
		return
	}
	t.Fatal("the registration was not rewritten")
}
