package pwcli

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const generatedTemplate = `// Code generated by tinybind templates; DO NOT EDIT.

package templates

import "github.com/shibukawa/tinybind-go/htmlbind"

type Error400Params struct{}

// Error400 binds Error400 to its parameters, producing a renderable fragment.
func Error400(params Error400Params) htmlbind.Fragment {
	return planError400Plan.Bind(params)
}

type memoRowParams struct{ Title string }

func memoRow(params memoRowParams) htmlbind.Fragment {
	return planMemoRowPlan.Bind(params)
}

type DocumentParams struct{ Children htmlbind.Fragment }

func Document(params DocumentParams) htmlbind.Fragment {
	return planDocumentPlan.Bind(params)
}

func BindDocument(params DocumentParams) htmlbind.Wrapper {
	return planDocumentPlan.BindWrapper(params, nil)
}

func notATemplate(value string) string { return value }
`

func TestScanFindsEveryGeneratedTemplate(t *testing.T) {
	directory := t.TempDir()
	path := filepath.Join(directory, "templates_pw_gen.go")
	if err := os.WriteFile(path, []byte(generatedTemplate), 0o644); err != nil {
		t.Fatal(err)
	}
	templates, err := scanStorybookTemplates(directory, plannedSources{})
	if err != nil {
		t.Fatal(err)
	}
	found := map[string]storybookTemplate{}
	for _, template := range templates {
		found[template.Name] = template
	}
	// An unexported template is exactly the one nothing outside the package can
	// render, so it is the one the storybook has to reach.
	memo, ok := found["memoRow"]
	if !ok {
		t.Fatalf("templates = %v, want the unexported one", found)
	}
	if memo.exported() || memo.Params != "memoRowParams" {
		t.Errorf("memoRow = %+v, want an unexported template with its params type", memo)
	}
	if !found["Error400"].exported() {
		t.Error("Error400 was not treated as exported")
	}
	if _, ok := found["notATemplate"]; ok {
		t.Error("a function that is not a template binder was registered")
	}
	if !found["BindDocument"].Document {
		t.Error("the wrapper binder was not recognised as the document shell")
	}
}

// The scan reads what this run is about to write, so check mode can report
// drift without anything having been written first.
func TestScanReadsPlannedOutputBeforeItIsOnDisk(t *testing.T) {
	directory := t.TempDir()
	path := filepath.Join(directory, "templates_pw_gen.go")
	sources := planned([]fileChange{{path: path, source: []byte(generatedTemplate)}})
	templates, err := scanStorybookTemplates(directory, sources)
	if err != nil {
		t.Fatal(err)
	}
	if len(templates) == 0 {
		t.Fatal("nothing was found in a file that exists only in the plan")
	}
}

func TestRegistrationReachesUnexportedTemplatesFromInsideThePackage(t *testing.T) {
	generated, err := storybookRegistration([]storybookTemplate{
		{Package: "templates", Name: "memoRow", Params: "memoRowParams"},
		{Package: "templates", Name: "BindDocument", Params: "DocumentParams", Document: true},
	})
	if err != nil {
		t.Fatal(err)
	}
	source := string(generated)
	if !strings.HasPrefix(source, "//go:build pwdev\n") {
		t.Error("the registration is not constrained to the development build mode")
	}
	if !strings.Contains(source, "package templates") {
		t.Error("the registration is not generated into the template's own package")
	}
	if !strings.Contains(source, `Name:      "memoRow"`) {
		t.Error("the unexported template was not registered")
	}
	if !strings.Contains(source, "pwstory.RegisterDocument(BindDocument(DocumentParams{}))") {
		t.Error("the document shell was not registered")
	}
}

func TestHarnessImportsEveryTemplatePackage(t *testing.T) {
	generated, err := storybookHarness("memoapp", []string{"handlers", "templates"})
	if err != nil {
		t.Fatal(err)
	}
	source := string(generated)
	if !strings.HasPrefix(source, "//go:build pwdev\n") {
		t.Error("the harness is not constrained to the development build mode")
	}
	for _, want := range []string{`_ "memoapp/handlers"`, `_ "memoapp/templates"`, "pwstory.ListenAndServe()"} {
		if !strings.Contains(source, want) {
			t.Errorf("the harness is missing %q:\n%s", want, source)
		}
	}
}

// storybookProject lays out a module with two template packages, each holding
// one generated template and the registration an earlier run wrote for it.
func storybookProject(t *testing.T) (string, projectConfig) {
	t.Helper()
	root := t.TempDir()
	write := func(relative, content string) {
		t.Helper()
		path := filepath.Join(root, filepath.FromSlash(relative))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("go.mod", "module memoapp\n\ngo 1.27\n")
	for _, directory := range []string{"handlers", "templates"} {
		write(directory+"/home.pw.html", "<template></template>\n")
		write(directory+"/home_pw_gen.go", generatedTemplate)
		write(directory+"/"+storybookFileName, "//go:build pwdev\n\npackage templates\n")
	}
	write(storybookDirectory+"/main_pw_gen.go", "//go:build pwdev\n\npackage main\n")
	var config projectConfig
	config.Generate.Templates = []string{"handlers", "templates"}
	return root, config
}

func removals(changes []fileChange) map[string]bool {
	removed := map[string]bool{}
	for _, change := range changes {
		if change.remove {
			removed[change.path] = true
		}
	}
	return removed
}

// The registration is compiled only under pwdev, so one that outlives its
// templates breaks pw dev and nothing else: it names functions that are gone,
// and go build never reads the file.
func TestStorybookRegistrationIsRemovedWithItsLastTemplate(t *testing.T) {
	root, config := storybookProject(t)
	handlers := filepath.Join(root, "handlers")
	if err := os.Remove(filepath.Join(handlers, "home.pw.html")); err != nil {
		t.Fatal(err)
	}
	// The template step has already planned the generated file's removal, and
	// the file is still on disk while this step runs.
	pending := []fileChange{{path: filepath.Join(handlers, "home_pw_gen.go"), remove: true}}

	changes, err := planStorybook(root, config, pending)
	if err != nil {
		t.Fatal(err)
	}
	removed := removals(changes)
	if !removed[filepath.Join(handlers, storybookFileName)] {
		t.Fatalf("the registration of a package with no template left was kept: %+v", changes)
	}
	if removed[filepath.Join(root, "templates", storybookFileName)] {
		t.Fatal("the registration of a package that still has templates was removed")
	}
	for _, change := range changes {
		if change.path == filepath.Join(root, storybookDirectory, "main_pw_gen.go") {
			if change.remove || strings.Contains(string(change.source), `"memoapp/handlers"`) {
				t.Fatalf("the harness still imports the emptied package:\n%s", change.source)
			}
		}
	}
}

// A template deleted from a package that keeps others must leave the
// registration in the same run, not in the one after it: the generated file it
// was read from is still on disk when the registration is planned.
func TestStorybookRegistrationForgetsATemplatePlannedForRemoval(t *testing.T) {
	root, config := storybookProject(t)
	templates := filepath.Join(root, "templates")
	const other = `package templates

import "github.com/shibukawa/tinybind-go/htmlbind"

type KeptParams struct{}

func Kept(params KeptParams) htmlbind.Fragment { return planKeptPlan.Bind(params) }
`
	if err := os.WriteFile(filepath.Join(templates, "kept_pw_gen.go"), []byte(other), 0o644); err != nil {
		t.Fatal(err)
	}
	pending := []fileChange{{path: filepath.Join(templates, "home_pw_gen.go"), remove: true}}
	changes, err := planStorybook(root, config, pending)
	if err != nil {
		t.Fatal(err)
	}
	for _, change := range changes {
		if change.path != filepath.Join(templates, storybookFileName) {
			continue
		}
		source := string(change.source)
		if !strings.Contains(source, `"Kept"`) || strings.Contains(source, `"Error400"`) {
			t.Fatalf("the registration names a template whose generated file is being removed:\n%s", source)
		}
		return
	}
	t.Fatal("the registration was not rewritten")
}

// With no template package left the harness has nothing to import.
func TestStorybookHarnessIsRemovedWithTheLastTemplatePackage(t *testing.T) {
	root, config := storybookProject(t)
	var pending []fileChange
	for _, directory := range []string{"handlers", "templates"} {
		if err := os.Remove(filepath.Join(root, directory, "home.pw.html")); err != nil {
			t.Fatal(err)
		}
		pending = append(pending, fileChange{path: filepath.Join(root, directory, "home_pw_gen.go"), remove: true})
	}
	changes, err := planStorybook(root, config, pending)
	if err != nil {
		t.Fatal(err)
	}
	removed := removals(changes)
	for _, path := range []string{
		filepath.Join(root, "handlers", storybookFileName),
		filepath.Join(root, "templates", storybookFileName),
		filepath.Join(root, storybookDirectory, "main_pw_gen.go"),
	} {
		if !removed[path] {
			t.Errorf("%s was kept", path)
		}
	}
}

// Before the first build there is no harness, and the pane says so rather than
// the console appearing to have lost it.
func TestStorybookPaneReportsAnAbsentHarness(t *testing.T) {
	storybook := &devStorybook{}
	recorder := httptest.NewRecorder()
	storybook.handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/", nil))
	if recorder.Code != http.StatusServiceUnavailable {
		t.Fatalf("status = %d, want 503", recorder.Code)
	}
	if !strings.Contains(recorder.Body.String(), "not answering") {
		t.Errorf("body = %q, want an explanation", recorder.Body)
	}
}

func TestStorybookPaneProxiesToTheHarness(t *testing.T) {
	harness := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("story at " + r.URL.Path))
	}))
	t.Cleanup(harness.Close)

	storybook := &devStorybook{}
	address := strings.TrimPrefix(harness.URL, "http://")
	storybook.address.Store(&address)

	recorder := httptest.NewRecorder()
	storybook.handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/story/templates/Home", nil))
	if body := recorder.Body.String(); body != "story at /story/templates/Home" {
		t.Errorf("body = %q, want the proxied response", body)
	}
}

func TestDisabledStorybookRegistersNoPane(t *testing.T) {
	root := writeProject(t, map[string]string{
		"popcornweb.toml": consoleProject + "\n[dev.console.storybook]\nenabled = false\n",
	})
	config, err := loadProjectConfig(root)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	if config.Console.Storybook {
		t.Error("the storybook stayed enabled")
	}
	for _, pane := range devConsolePanes(root, config, developmentServer{}, nil, nil, nil) {
		if pane.Slug == "storybook" && pane.Enabled() {
			t.Error("a disabled storybook still produced a working pane")
		}
	}
}
