package pwcli

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const generatedTemplate = `// Code generated by tinybind templates; DO NOT EDIT.

package templates

import "github.com/shibukawa/tinybind-go/htmlbind"

type Error400Params struct{}

// Error400 binds Error400 to its parameters, producing a renderable fragment.
func Error400(params Error400Params) htmlbind.Fragment {
	return planError400Plan.Bind(params)
}

type memoRowParams struct{ Title string }

func memoRow(params memoRowParams) htmlbind.Fragment {
	return planMemoRowPlan.Bind(params)
}

type DocumentParams struct{ Children htmlbind.Fragment }

func Document(params DocumentParams) htmlbind.Fragment {
	return planDocumentPlan.Bind(params)
}

func BindDocument(params DocumentParams) htmlbind.Wrapper {
	return planDocumentPlan.BindWrapper(params, nil)
}

func notATemplate(value string) string { return value }
`

func TestScanFindsEveryGeneratedTemplate(t *testing.T) {
	directory := t.TempDir()
	path := filepath.Join(directory, "templates_pw_gen.go")
	if err := os.WriteFile(path, []byte(generatedTemplate), 0o644); err != nil {
		t.Fatal(err)
	}
	templates, err := scanStorybookTemplates(directory, plannedSources{})
	if err != nil {
		t.Fatal(err)
	}
	found := map[string]storybookTemplate{}
	for _, template := range templates {
		found[template.Name] = template
	}
	// An unexported template is exactly the one nothing outside the package can
	// render, so it is the one the storybook has to reach.
	memo, ok := found["memoRow"]
	if !ok {
		t.Fatalf("templates = %v, want the unexported one", found)
	}
	if memo.exported() || memo.Params != "memoRowParams" {
		t.Errorf("memoRow = %+v, want an unexported template with its params type", memo)
	}
	if !found["Error400"].exported() {
		t.Error("Error400 was not treated as exported")
	}
	if _, ok := found["notATemplate"]; ok {
		t.Error("a function that is not a template binder was registered")
	}
	if !found["BindDocument"].Document {
		t.Error("the wrapper binder was not recognised as the document shell")
	}
}

// The scan reads what this run is about to write, so check mode can report
// drift without anything having been written first.
func TestScanReadsPlannedOutputBeforeItIsOnDisk(t *testing.T) {
	directory := t.TempDir()
	path := filepath.Join(directory, "templates_pw_gen.go")
	sources := planned([]fileChange{{path: path, source: []byte(generatedTemplate)}})
	templates, err := scanStorybookTemplates(directory, sources)
	if err != nil {
		t.Fatal(err)
	}
	if len(templates) == 0 {
		t.Fatal("nothing was found in a file that exists only in the plan")
	}
}

func TestRegistrationReachesUnexportedTemplatesFromInsideThePackage(t *testing.T) {
	generated, err := storybookRegistration([]storybookTemplate{
		{Package: "templates", Name: "memoRow", Params: "memoRowParams"},
		{Package: "templates", Name: "BindDocument", Params: "DocumentParams", Document: true},
	})
	if err != nil {
		t.Fatal(err)
	}
	source := string(generated)
	if !strings.HasPrefix(source, "//go:build pwdev\n") {
		t.Error("the registration is not constrained to the development build mode")
	}
	if !strings.Contains(source, "package templates") {
		t.Error("the registration is not generated into the template's own package")
	}
	if !strings.Contains(source, `Name:      "memoRow"`) {
		t.Error("the unexported template was not registered")
	}
	if !strings.Contains(source, "pwstory.RegisterDocument(BindDocument(DocumentParams{}))") {
		t.Error("the document shell was not registered")
	}
}

func TestHarnessImportsEveryTemplatePackage(t *testing.T) {
	generated, err := storybookHarness("memoapp", []string{"handlers", "templates"})
	if err != nil {
		t.Fatal(err)
	}
	source := string(generated)
	if !strings.HasPrefix(source, "//go:build pwdev\n") {
		t.Error("the harness is not constrained to the development build mode")
	}
	for _, want := range []string{`_ "memoapp/handlers"`, `_ "memoapp/templates"`, "pwstory.ListenAndServe()"} {
		if !strings.Contains(source, want) {
			t.Errorf("the harness is missing %q:\n%s", want, source)
		}
	}
}

// Before the first build there is no harness, and the pane says so rather than
// the console appearing to have lost it.
func TestStorybookPaneReportsAnAbsentHarness(t *testing.T) {
	storybook := &devStorybook{}
	recorder := httptest.NewRecorder()
	storybook.handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/", nil))
	if recorder.Code != http.StatusServiceUnavailable {
		t.Fatalf("status = %d, want 503", recorder.Code)
	}
	if !strings.Contains(recorder.Body.String(), "not answering") {
		t.Errorf("body = %q, want an explanation", recorder.Body)
	}
}

func TestStorybookPaneProxiesToTheHarness(t *testing.T) {
	harness := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("story at " + r.URL.Path))
	}))
	t.Cleanup(harness.Close)

	storybook := &devStorybook{}
	address := strings.TrimPrefix(harness.URL, "http://")
	storybook.address.Store(&address)

	recorder := httptest.NewRecorder()
	storybook.handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/story/templates/Home", nil))
	if body := recorder.Body.String(); body != "story at /story/templates/Home" {
		t.Errorf("body = %q, want the proxied response", body)
	}
}

func TestDisabledStorybookRegistersNoPane(t *testing.T) {
	root := writeProject(t, map[string]string{
		"popcornweb.toml": consoleProject + "\n[dev.console.storybook]\nenabled = false\n",
	})
	config, err := loadProjectConfig(root)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	if config.Console.Storybook {
		t.Error("the storybook stayed enabled")
	}
	for _, pane := range devConsolePanes(root, config, developmentServer{}, nil, nil, nil) {
		if pane.Slug == "storybook" && pane.Enabled() {
			t.Error("a disabled storybook still produced a working pane")
		}
	}
}
