// Code generated by tinybind HTML templates; DO NOT EDIT.

package id_

import (
	"context"

	"github.com/shibukawa/tinybind-go/htmlbind"
	"github.com/shibukawa/tinybind-go/htmlbind/delta"
)

type View struct {
	Name string
	Page int
}

type PageParams struct {
	Id   string
	Page *int
}

type planPageOpsVal1 struct {
	Outer PageParams
	View  View
}

var planPageOpsVal1Ops = htmlbind.Builder[planPageOpsVal1]{}

var planPageOps = htmlbind.Builder[PageParams]{}

// planPageInput canonically encodes the declared inputs of Page.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planPageInput(p PageParams) string {
	return delta.CanonJoin(
		delta.CanonString[string](p.Id),
		delta.CanonOptional(p.Page, delta.CanonInt),
	)
}

var planPageBoundary = &htmlbind.Boundary[PageParams]{
	ComponentID: "id_.page.Page",
	Attr:        "data-tb-id",
	Input:       planPageInput,
}

var planPagePlan = &htmlbind.Plan[PageParams]{
	Head:        []string{"<script src=\"/public/generated/page.script.564ef8d0adbe.js\" type=\"module\"></script>"},
	HeadSources: []string{""},
	Assets:      []htmlbind.Asset{{ID: "page.script.564ef8d0adbe", Type: "text/javascript", URL: "/public/generated/page.script.564ef8d0adbe.js", Scope: "id_.page.Page"}},
	Boundary:    planPageBoundary,
	Ops: []htmlbind.Op[PageParams]{
		planPageOps.ValErrCtx(
			func(ctx context.Context, p PageParams) (View, error) { return LoadUser(ctx, p.Id, p.Page) },
			func(p PageParams, value View) planPageOpsVal1 { return planPageOpsVal1{Outer: p, View: value} },
			[]htmlbind.Op[planPageOpsVal1]{
				planPageOpsVal1Ops.Static("  <section"),
				planPageOpsVal1Ops.BoundaryAttr(),
				planPageOpsVal1Ops.Static(" data-tb-component=\"id_.page.Page\">  <h1 data-tb-on=\"click:highlight\">"),
				planPageOpsVal1Ops.Text(func(p planPageOpsVal1) string { return p.View.Name }),
				planPageOpsVal1Ops.Static("</h1> <p>page "),
				planPageOpsVal1Ops.Raw(func(p planPageOpsVal1) string { return htmlbind.FormatInt(p.View.Page) }),
				planPageOpsVal1Ops.Static("</p> <button data-tb-action=\"/_action/00369cf962b6/Rename\" data-target=\"#name\">rename</button> <form data-tb-action=\"/_action/d71506d06c1e/Retire\" method=\"post\"><input type=\"hidden\" name=\"_action\" value=\"d71506d06c1e/Retire\" />"),
				planPageOpsVal1Ops.CSRFField("_csrf"),
				planPageOpsVal1Ops.Static(" <input type=\"text\" name=\"reason\" /> <button type=\"submit\">retire</button> </form> </section> "),
			}),
	},
}

// Page binds Page to its parameters, producing a renderable fragment.
func Page(params PageParams) htmlbind.Fragment { return planPagePlan.Bind(params) }
