// Code generated by configbind/codegen; DO NOT EDIT.

package auth

import (
	"fmt"
	"strconv"
	"time"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerConfigDefinition0()
	registerSessionLifetimeConfigDefinition1()
}

func registerConfigDefinition0() {
	configbind.Register[Config](configbind.Definition{
		TypeName: "github.com/shibukawa/popcornweb/plugin/auth.Config",
		Prefix:   "auth",
		Doc:      "Config is the [auth] runtime binding. It is registered when this package is imported",
		KnownKeys: []string{
			"auth.enabled",
			"auth.backend",
			"auth.mode",
			"auth.login_path",
			"auth.callback_path",
			"auth.logout_path",
			"auth.post_login_path",
			"auth.recent_auth_max_age",
			"auth.shared_device",
			"auth.assurance.policy",
			"auth.assurance.hint.enabled",
			"auth.assurance.hint.name",
			"auth.assurance.hint.secret",
			"auth.assurance.hint.previous_secrets",
			"auth.assurance.hint.ttl",
			"auth.assurance.hint.idle_timeout",
			"auth.assurance.presence.enabled",
			"auth.assurance.presence.interval",
			"auth.assurance.presence.absent_after",
			"auth.protection.include",
			"auth.protection.exclude",
			"auth.protection.unauthenticated",
			"auth.registration.policy",
			"auth.recovery.policy",
			"auth.bootstrap.issue_ttl",
			"auth.bootstrap.enrollment_ttl",
			"auth.bootstrap.max_attempts",
			"auth.oidc.issuer",
			"auth.oidc.client_id",
			"auth.oidc.client_secret",
			"auth.oidc.redirect_url",
			"auth.oidc.scopes",
			"auth.oidc.endpoint_hosts",
			"auth.oidc.identity_claim",
			"auth.oidc.admission",
			"auth.oidc.auto_provision",
			"auth.oidc.claim.path",
			"auth.oidc.claim.values",
			"auth.oidc.claim.match",
			"auth.oidc.registered_claims",
			"auth.oidc.logout_scope",
			"auth.oidc.provider_logout",
			"auth.oidc.allow_global_logout_request",
			"auth.oidc.allow_loopback_http",
			"auth.oauth.provider",
			"auth.oauth.client_id",
			"auth.oauth.client_secret",
			"auth.oauth.redirect_url",
			"auth.oauth.scopes",
			"auth.oauth.identity_claim",
			"auth.oauth.admission",
			"auth.oauth.auto_provision",
			"auth.oauth.claim.path",
			"auth.oauth.claim.values",
			"auth.oauth.claim.match",
			"auth.oauth.registered_claims",
			"auth.oauth.allow_loopback_http",
			"auth.passkey.path",
			"auth.passkey.rp_id",
			"auth.passkey.rp_name",
			"auth.passkey.origins",
			"auth.passkey.user_verification",
			"auth.passkey.discoverable",
			"auth.jwt.issuer",
			"auth.jwt.audience",
			"auth.jwt.audience_match",
			"auth.jwt.algorithms",
			"auth.jwt.required_token_type",
			"auth.jwt.required_scopes",
			"auth.jwt.discovery",
			"auth.jwt.jwks_uri",
			"auth.jwt.leeway",
			"auth.jwt.max_token_lifetime",
			"auth.jwt.max_token_bytes",
			"auth.jwt.jwks_refresh_cooldown",
			"auth.jwt.allow_loopback_http",
			"auth.jwt.identity_claim",
			"auth.jwt.admission",
			"auth.jwt.auto_provision",
			"auth.jwt.claim.path",
			"auth.jwt.claim.values",
			"auth.jwt.claim.match",
			"auth.jwt.registered_claims",
			"auth.jwt.revocation.mode",
			"auth.jwt.revocation.on_unavailable",
			"auth.jwt.revocation.max_propagation_delay",
			"auth.jwt.dev.trust_unverified_tokens",
		},
		Defaults: map[string]string{
			"auth.enabled":                          "false",
			"auth.backend":                          "rdb",
			"auth.mode":                             "oidc_only",
			"auth.login_path":                       "/auth/login",
			"auth.callback_path":                    "/auth/callback",
			"auth.logout_path":                      "/auth/logout",
			"auth.post_login_path":                  "/",
			"auth.recent_auth_max_age":              "5m",
			"auth.shared_device":                    "false",
			"auth.assurance.hint.enabled":           "false",
			"auth.assurance.hint.name":              "pw_hint",
			"auth.assurance.hint.ttl":               "720h",
			"auth.assurance.hint.idle_timeout":      "336h",
			"auth.assurance.presence.enabled":       "false",
			"auth.assurance.presence.interval":      "1m",
			"auth.assurance.presence.absent_after":  "30m",
			"auth.protection.unauthenticated":       "redirect",
			"auth.bootstrap.issue_ttl":              "24h",
			"auth.bootstrap.enrollment_ttl":         "10m",
			"auth.bootstrap.max_attempts":           "5",
			"auth.oidc.identity_claim":              "sub",
			"auth.oidc.admission":                   "authenticated",
			"auth.oidc.auto_provision":              "true",
			"auth.oidc.claim.match":                 "any",
			"auth.oidc.logout_scope":                "reconfirm",
			"auth.oidc.provider_logout":             "false",
			"auth.oidc.allow_global_logout_request": "false",
			"auth.oidc.allow_loopback_http":         "false",
			"auth.oauth.identity_claim":             "sub",
			"auth.oauth.admission":                  "authenticated",
			"auth.oauth.auto_provision":             "true",
			"auth.oauth.claim.match":                "any",
			"auth.oauth.allow_loopback_http":        "false",
			"auth.passkey.path":                     "/auth/passkey",
			"auth.passkey.user_verification":        "required",
			"auth.passkey.discoverable":             "preferred",
			"auth.jwt.audience_match":               "any",
			"auth.jwt.required_token_type":          "at+jwt",
			"auth.jwt.discovery":                    "oidc",
			"auth.jwt.leeway":                       "30s",
			"auth.jwt.max_token_bytes":              "8192",
			"auth.jwt.jwks_refresh_cooldown":        "1m",
			"auth.jwt.allow_loopback_http":          "false",
			"auth.jwt.identity_claim":               "sub",
			"auth.jwt.auto_provision":               "false",
			"auth.jwt.claim.match":                  "any",
			"auth.jwt.revocation.on_unavailable":    "refuse",
			"auth.jwt.dev.trust_unverified_tokens":  "false",
		},
		DependsOn: map[string][]configbind.Dependency{
			"auth.backend":                              {{Key: "auth.enabled"}},
			"auth.mode":                                 {{Key: "auth.enabled"}},
			"auth.login_path":                           {{Key: "auth.enabled"}},
			"auth.callback_path":                        {{Key: "auth.enabled"}},
			"auth.logout_path":                          {{Key: "auth.enabled"}},
			"auth.post_login_path":                      {{Key: "auth.enabled"}},
			"auth.recent_auth_max_age":                  {{Key: "auth.enabled"}},
			"auth.shared_device":                        {{Key: "auth.enabled"}},
			"auth.assurance.policy":                     {{Key: "auth.enabled"}},
			"auth.assurance.hint.enabled":               {{Key: "auth.enabled"}},
			"auth.assurance.hint.name":                  {{Key: "auth.enabled"}, {Key: "auth.assurance.hint.enabled"}},
			"auth.assurance.hint.secret":                {{Key: "auth.enabled"}, {Key: "auth.assurance.hint.enabled"}},
			"auth.assurance.hint.previous_secrets":      {{Key: "auth.enabled"}, {Key: "auth.assurance.hint.enabled"}},
			"auth.assurance.hint.ttl":                   {{Key: "auth.enabled"}, {Key: "auth.assurance.hint.enabled"}},
			"auth.assurance.hint.idle_timeout":          {{Key: "auth.enabled"}, {Key: "auth.assurance.hint.enabled"}},
			"auth.assurance.presence.enabled":           {{Key: "auth.enabled"}},
			"auth.assurance.presence.interval":          {{Key: "auth.enabled"}, {Key: "auth.assurance.presence.enabled"}},
			"auth.assurance.presence.absent_after":      {{Key: "auth.enabled"}, {Key: "auth.assurance.presence.enabled"}},
			"auth.protection.include":                   {{Key: "auth.enabled"}},
			"auth.protection.exclude":                   {{Key: "auth.enabled"}},
			"auth.protection.unauthenticated":           {{Key: "auth.enabled"}},
			"auth.registration.policy":                  {{Key: "auth.enabled"}},
			"auth.recovery.policy":                      {{Key: "auth.enabled"}},
			"auth.bootstrap.issue_ttl":                  {{Key: "auth.enabled"}},
			"auth.bootstrap.enrollment_ttl":             {{Key: "auth.enabled"}},
			"auth.bootstrap.max_attempts":               {{Key: "auth.enabled"}},
			"auth.oidc.issuer":                          {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.client_id":                       {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.client_secret":                   {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.redirect_url":                    {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.scopes":                          {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.endpoint_hosts":                  {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.identity_claim":                  {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.admission":                       {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.auto_provision":                  {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.claim.path":                      {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.claim.values":                    {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.claim.match":                     {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.registered_claims":               {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.logout_scope":                    {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.provider_logout":                 {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.allow_global_logout_request":     {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oidc.allow_loopback_http":             {{Key: "auth.mode", Op: "=", Values: []string{"oidc_only", "oidc_passkey"}}},
			"auth.oauth.provider":                       {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.client_id":                      {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.client_secret":                  {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.redirect_url":                   {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.scopes":                         {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.identity_claim":                 {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.admission":                      {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.auto_provision":                 {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.claim.path":                     {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.claim.values":                   {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.claim.match":                    {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.registered_claims":              {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.oauth.allow_loopback_http":            {{Key: "auth.mode", Op: "=", Values: []string{"oauth_only"}}},
			"auth.passkey.path":                         {{Key: "auth.mode", Op: "=", Values: []string{"oidc_passkey", "passkey_only"}}},
			"auth.passkey.rp_id":                        {{Key: "auth.mode", Op: "=", Values: []string{"oidc_passkey", "passkey_only"}}},
			"auth.passkey.rp_name":                      {{Key: "auth.mode", Op: "=", Values: []string{"oidc_passkey", "passkey_only"}}},
			"auth.passkey.origins":                      {{Key: "auth.mode", Op: "=", Values: []string{"oidc_passkey", "passkey_only"}}},
			"auth.passkey.user_verification":            {{Key: "auth.mode", Op: "=", Values: []string{"oidc_passkey", "passkey_only"}}},
			"auth.passkey.discoverable":                 {{Key: "auth.mode", Op: "=", Values: []string{"oidc_passkey", "passkey_only"}}},
			"auth.jwt.issuer":                           {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.audience":                         {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.audience_match":                   {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.algorithms":                       {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.required_token_type":              {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.required_scopes":                  {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.discovery":                        {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.jwks_uri":                         {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.leeway":                           {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.max_token_lifetime":               {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.max_token_bytes":                  {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.jwks_refresh_cooldown":            {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.allow_loopback_http":              {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.identity_claim":                   {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.admission":                        {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.auto_provision":                   {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.claim.path":                       {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.claim.values":                     {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.claim.match":                      {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.registered_claims":                {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.revocation.mode":                  {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.revocation.on_unavailable":        {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.revocation.max_propagation_delay": {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
			"auth.jwt.dev.trust_unverified_tokens":      {{Key: "auth.mode", Op: "=", Values: []string{"jwt_only"}}},
		},
		Secrets: map[string]string{
			"auth.assurance.hint.secret":           "mask",
			"auth.assurance.hint.previous_secrets": "mask",
			"auth.bootstrap.issue_ttl":             "show",
			"auth.bootstrap.enrollment_ttl":        "show",
			"auth.bootstrap.max_attempts":          "show",
			"auth.oidc.client_secret":              "mask",
			"auth.oauth.client_secret":             "mask",
		},
		Summary: map[string]string{
			"auth.recent_auth_max_age":      "omit",
			"auth.bootstrap":                "omit",
			"auth.bootstrap.issue_ttl":      "omit",
			"auth.bootstrap.enrollment_ttl": "omit",
			"auth.bootstrap.max_attempts":   "omit",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "auth", Key: "enabled", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "backend", Help: "storage backend of the authentication tables: rdb or dynamo", Enum: []string{"rdb", "dynamo"}},
			{Prefix: "auth", Key: "mode", Help: "oidc_only, oidc_passkey, passkey_only, oauth_only, or jwt_only", Enum: []string{"oidc_only", "oidc_passkey", "passkey_only", "oauth_only", "jwt_only"}},
			{Prefix: "auth", Key: "login_path", Help: "path that starts the provider flow"},
			{Prefix: "auth", Key: "callback_path"},
			{Prefix: "auth", Key: "logout_path"},
			{Prefix: "auth", Key: "post_login_path", Help: "path a completed login lands on"},
			{Prefix: "auth", Key: "recent_auth_max_age", Help: "how recently a request must have authenticated to change a login method"},
			{Prefix: "auth", Key: "shared_device", Help: "declare that browsers are shared, coupling the settings that hide one user from the next", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "assurance.hint.enabled", Help: "remember who last signed in, to shorten the next sign-in", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "assurance.hint.name", Help: "cookie name"},
			{Prefix: "auth", Key: "assurance.hint.secret", Env: "AUTH_HINT_SECRET", Help: "base64 secret of at least 256 bits that seals the hint"},
			{Prefix: "auth", Key: "assurance.hint.previous_secrets", Help: "retired secrets kept readable during a rotation", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "assurance.hint.ttl", Help: "how long a hint may live at all"},
			{Prefix: "auth", Key: "assurance.hint.idle_timeout", Help: "how long since the last successful login a hint survives"},
			{Prefix: "auth", Key: "assurance.presence.enabled", Help: "accept presence reports from the browser", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "assurance.presence.interval", Help: "how often a browser reports"},
			{Prefix: "auth", Key: "assurance.presence.absent_after", Help: "end the session after this long with no interaction"},
			{Prefix: "auth", Key: "protection.include", Help: "protected path pattern", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "protection.exclude", Help: "public path pattern", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "protection.unauthenticated", Help: "redirect or unauthorized"},
			{Prefix: "auth", Key: "registration.policy", Help: "disabled, oidc, invite, administrator, or open"},
			{Prefix: "auth", Key: "recovery.policy", Help: "oidc, administrator, or application"},
			{Prefix: "auth", Key: "bootstrap.issue_ttl", Help: "how long an issued secret stays redeemable"},
			{Prefix: "auth", Key: "bootstrap.enrollment_ttl", Help: "how long an enrollment stays open after a redemption"},
			{Prefix: "auth", Key: "bootstrap.max_attempts", Help: "redemption attempts before the credential is spent"},
			{Prefix: "auth", Key: "oidc.issuer", Env: "AUTH_OIDC_ISSUER"},
			{Prefix: "auth", Key: "oidc.client_id", Env: "AUTH_OIDC_CLIENT_ID"},
			{Prefix: "auth", Key: "oidc.client_secret", Env: "AUTH_OIDC_CLIENT_SECRET"},
			{Prefix: "auth", Key: "oidc.redirect_url"},
			{Prefix: "auth", Key: "oidc.scopes", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "oidc.endpoint_hosts", Help: "hosts the discovery document may point endpoints at; empty accepts any", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "oidc.identity_claim", Help: "verified claim that identifies a local account"},
			{Prefix: "auth", Key: "oidc.admission", Help: "authenticated, claim, registered, or existing"},
			{Prefix: "auth", Key: "oidc.auto_provision", Help: "AutoProvision permits an unknown verified identity to create an account through the registered account resolver", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "oidc.claim.path", Help: "JSON Pointer into verified claims"},
			{Prefix: "auth", Key: "oidc.claim.values", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "oidc.claim.match", Help: "any or all"},
			{Prefix: "auth", Key: "oidc.registered_claims", Help: "claims compared against the allowlist; defaults to identity_claim", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "oidc.logout_scope", Help: "what a logout does to the provider session: reconfirm or global", Enum: []string{"reconfirm", "global"}},
			{Prefix: "auth", Key: "oidc.provider_logout", Help: "removed; use auth.oidc.logout_scope", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "oidc.allow_global_logout_request", Help: "permit a logout request to escalate to a global sign-out", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "oidc.allow_loopback_http", Help: "permit an http loopback issuer during development", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "oauth.provider", Help: "OAuth login provider; x is X, formerly Twitter", Enum: []string{"x"}},
			{Prefix: "auth", Key: "oauth.client_id", Env: "AUTH_OAUTH_CLIENT_ID"},
			{Prefix: "auth", Key: "oauth.client_secret", Env: "AUTH_OAUTH_CLIENT_SECRET"},
			{Prefix: "auth", Key: "oauth.redirect_url", Help: "RedirectURL is the absolute callback URL registered with the provider"},
			{Prefix: "auth", Key: "oauth.scopes", Help: "scopes to request; empty asks for the provider's minimum login set", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "oauth.identity_claim", Help: "profile claim that identifies a local account; sub is the provider's own identifier"},
			{Prefix: "auth", Key: "oauth.admission", Help: "authenticated, claim, registered, or existing"},
			{Prefix: "auth", Key: "oauth.auto_provision", Help: "permit an unknown profile to create an account through the registered account resolver", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "oauth.claim.path", Help: "JSON Pointer into verified claims"},
			{Prefix: "auth", Key: "oauth.claim.values", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "oauth.claim.match", Help: "any or all"},
			{Prefix: "auth", Key: "oauth.registered_claims", Help: "claims compared against the allowlist; defaults to identity_claim", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "oauth.allow_loopback_http", Help: "permit an http loopback redirect URL during development", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "passkey.path", Help: "base path of the ceremony endpoints"},
			{Prefix: "auth", Key: "passkey.rp_id", Help: "relying party domain; localhost during development"},
			{Prefix: "auth", Key: "passkey.rp_name", Help: "relying party display name"},
			{Prefix: "auth", Key: "passkey.origins", Help: "origin the browser reaches this deployment on", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "passkey.user_verification", Help: "required, preferred, or discouraged"},
			{Prefix: "auth", Key: "passkey.discoverable", Help: "required or preferred"},
			{Prefix: "auth", Key: "jwt.issuer", Env: "AUTH_JWT_ISSUER", Help: "exact iss claim value this deployment accepts"},
			{Prefix: "auth", Key: "jwt.audience", Help: "aud value naming this API; required", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "jwt.audience_match", Help: "any or all", Enum: []string{"any", "all"}},
			{Prefix: "auth", Key: "jwt.algorithms", Help: "exact verification algorithm allowlist; required, e.g. [\"RS256\"]", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "jwt.required_token_type", Help: "typ header to demand; empty accepts an absent typ"},
			{Prefix: "auth", Key: "jwt.required_scopes", Help: "scope values every request must carry", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "jwt.discovery", Help: "oidc, oauth, or manual", Enum: []string{"oidc", "oauth", "manual"}},
			{Prefix: "auth", Key: "jwt.jwks_uri", Help: "signing key set, for manual discovery"},
			{Prefix: "auth", Key: "jwt.leeway", Help: "clock skew allowance"},
			{Prefix: "auth", Key: "jwt.max_token_lifetime", Help: "longest exp-minus-iat accepted; required"},
			{Prefix: "auth", Key: "jwt.max_token_bytes", Help: "largest compact token accepted"},
			{Prefix: "auth", Key: "jwt.jwks_refresh_cooldown", Help: "shortest interval between unknown-kid refreshes"},
			{Prefix: "auth", Key: "jwt.allow_loopback_http", Help: "permit an http loopback issuer during development", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "jwt.identity_claim", Help: "verified claim that identifies a local account"},
			{Prefix: "auth", Key: "jwt.admission", Help: "authenticated, claim, registered, or existing; required"},
			{Prefix: "auth", Key: "jwt.auto_provision", Help: "permit an unknown verified identity to create an account", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "jwt.claim.path", Help: "JSON Pointer into verified claims"},
			{Prefix: "auth", Key: "jwt.claim.values", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "jwt.claim.match", Help: "any or all"},
			{Prefix: "auth", Key: "jwt.registered_claims", Help: "claims compared against the allowlist; defaults to identity_claim", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "jwt.revocation.mode", Help: "off, token, subject, or both; required in jwt_only"},
			{Prefix: "auth", Key: "jwt.revocation.on_unavailable", Help: "refuse or admit when the store cannot answer", Enum: []string{"refuse", "admit"}},
			{Prefix: "auth", Key: "jwt.revocation.max_propagation_delay", Help: "how stale a cached revocation answer may be; zero disables the cache"},
			{Prefix: "auth", Key: "jwt.dev.trust_unverified_tokens", Help: "development only: admit a token without verifying it", Kind: cliparser.KindBool},
		},
		Apply: applyConfigDefinition0,
		Scaffold: []configbind.ScaffoldField{
			{Key: "enabled", Kind: configbind.ScaffoldBool, Default: "false"},
			{Key: "backend", Kind: configbind.ScaffoldString, Default: "rdb", Help: "storage backend of the authentication tables: rdb or dynamo", Enum: []string{"rdb", "dynamo"}},
			{Key: "mode", Kind: configbind.ScaffoldString, Default: "oidc_only", Help: "oidc_only, oidc_passkey, passkey_only, oauth_only, or jwt_only", Enum: []string{"oidc_only", "oidc_passkey", "passkey_only", "oauth_only", "jwt_only"}},
			{Key: "login_path", Kind: configbind.ScaffoldString, Default: "/auth/login", Help: "path that starts the provider flow"},
			{Key: "callback_path", Kind: configbind.ScaffoldString, Default: "/auth/callback"},
			{Key: "logout_path", Kind: configbind.ScaffoldString, Default: "/auth/logout"},
			{Key: "post_login_path", Kind: configbind.ScaffoldString, Default: "/", Help: "path a completed login lands on"},
			{Key: "recent_auth_max_age", Kind: configbind.ScaffoldDuration, Default: "5m", Help: "how recently a request must have authenticated to change a login method"},
			{Key: "shared_device", Kind: configbind.ScaffoldBool, Default: "false", Help: "declare that browsers are shared, coupling the settings that hide one user from the next"},
			{Key: "assurance.policy", Kind: configbind.ScaffoldTableArray, Help: "named freshness windows a handler can require by name", Nested: []configbind.ScaffoldField{
				{Key: "name", Kind: configbind.ScaffoldString, Help: "name a handler passes to auth.Policy"},
				{Key: "max_age", Kind: configbind.ScaffoldDuration, Help: "how old a proof may be; zero means prove again for this operation"},
				{Key: "confirm", Kind: configbind.ScaffoldBool, Default: "false", Help: "require a re-proof this guard asked for; a login never counts"},
			}},
			{Key: "assurance.hint.enabled", Kind: configbind.ScaffoldBool, Default: "false", Help: "remember who last signed in, to shorten the next sign-in"},
			{Key: "assurance.hint.name", Kind: configbind.ScaffoldString, Default: "pw_hint", Help: "cookie name"},
			{Key: "assurance.hint.secret", Kind: configbind.ScaffoldString, Env: "AUTH_HINT_SECRET", Help: "base64 secret of at least 256 bits that seals the hint"},
			{Key: "assurance.hint.previous_secrets", Kind: configbind.ScaffoldStringSlice, Help: "retired secrets kept readable during a rotation"},
			{Key: "assurance.hint.ttl", Kind: configbind.ScaffoldDuration, Default: "720h", Help: "how long a hint may live at all"},
			{Key: "assurance.hint.idle_timeout", Kind: configbind.ScaffoldDuration, Default: "336h", Help: "how long since the last successful login a hint survives"},
			{Key: "assurance.presence.enabled", Kind: configbind.ScaffoldBool, Default: "false", Help: "accept presence reports from the browser"},
			{Key: "assurance.presence.interval", Kind: configbind.ScaffoldDuration, Default: "1m", Help: "how often a browser reports"},
			{Key: "assurance.presence.absent_after", Kind: configbind.ScaffoldDuration, Default: "30m", Help: "end the session after this long with no interaction"},
			{Key: "protection.include", Kind: configbind.ScaffoldStringSlice, Help: "protected path pattern"},
			{Key: "protection.exclude", Kind: configbind.ScaffoldStringSlice, Help: "public path pattern"},
			{Key: "protection.unauthenticated", Kind: configbind.ScaffoldString, Default: "redirect", Help: "redirect or unauthorized"},
			{Key: "registration.policy", Kind: configbind.ScaffoldString, Help: "disabled, oidc, invite, administrator, or open"},
			{Key: "recovery.policy", Kind: configbind.ScaffoldString, Help: "oidc, administrator, or application"},
			{Key: "bootstrap.issue_ttl", Kind: configbind.ScaffoldDuration, Default: "24h", Help: "how long an issued secret stays redeemable"},
			{Key: "bootstrap.enrollment_ttl", Kind: configbind.ScaffoldDuration, Default: "10m", Help: "how long an enrollment stays open after a redemption"},
			{Key: "bootstrap.max_attempts", Kind: configbind.ScaffoldInt, Default: "5", Help: "redemption attempts before the credential is spent"},
			{Key: "oidc.issuer", Kind: configbind.ScaffoldString, Env: "AUTH_OIDC_ISSUER"},
			{Key: "oidc.client_id", Kind: configbind.ScaffoldString, Env: "AUTH_OIDC_CLIENT_ID"},
			{Key: "oidc.client_secret", Kind: configbind.ScaffoldString, Env: "AUTH_OIDC_CLIENT_SECRET"},
			{Key: "oidc.redirect_url", Kind: configbind.ScaffoldString},
			{Key: "oidc.scopes", Kind: configbind.ScaffoldStringSlice},
			{Key: "oidc.endpoint_hosts", Kind: configbind.ScaffoldStringSlice, Help: "hosts the discovery document may point endpoints at; empty accepts any"},
			{Key: "oidc.identity_claim", Kind: configbind.ScaffoldString, Default: "sub", Help: "verified claim that identifies a local account"},
			{Key: "oidc.admission", Kind: configbind.ScaffoldString, Default: "authenticated", Help: "authenticated, claim, registered, or existing"},
			{Key: "oidc.auto_provision", Kind: configbind.ScaffoldBool, Default: "true", Help: "AutoProvision permits an unknown verified identity to create an account through the registered account resolver"},
			{Key: "oidc.claim.path", Kind: configbind.ScaffoldString, Help: "JSON Pointer into verified claims"},
			{Key: "oidc.claim.values", Kind: configbind.ScaffoldStringSlice},
			{Key: "oidc.claim.match", Kind: configbind.ScaffoldString, Default: "any", Help: "any or all"},
			{Key: "oidc.registered_claims", Kind: configbind.ScaffoldStringSlice, Help: "claims compared against the allowlist; defaults to identity_claim"},
			{Key: "oidc.logout_scope", Kind: configbind.ScaffoldString, Default: "reconfirm", Help: "what a logout does to the provider session: reconfirm or global", Enum: []string{"reconfirm", "global"}},
			{Key: "oidc.provider_logout", Kind: configbind.ScaffoldBool, Default: "false", Help: "removed; use auth.oidc.logout_scope"},
			{Key: "oidc.allow_global_logout_request", Kind: configbind.ScaffoldBool, Default: "false", Help: "permit a logout request to escalate to a global sign-out"},
			{Key: "oidc.allow_loopback_http", Kind: configbind.ScaffoldBool, Default: "false", Help: "permit an http loopback issuer during development"},
			{Key: "oauth.provider", Kind: configbind.ScaffoldString, Help: "OAuth login provider; x is X, formerly Twitter", Enum: []string{"x"}},
			{Key: "oauth.client_id", Kind: configbind.ScaffoldString, Env: "AUTH_OAUTH_CLIENT_ID"},
			{Key: "oauth.client_secret", Kind: configbind.ScaffoldString, Env: "AUTH_OAUTH_CLIENT_SECRET"},
			{Key: "oauth.redirect_url", Kind: configbind.ScaffoldString, Help: "RedirectURL is the absolute callback URL registered with the provider"},
			{Key: "oauth.scopes", Kind: configbind.ScaffoldStringSlice, Help: "scopes to request; empty asks for the provider's minimum login set"},
			{Key: "oauth.identity_claim", Kind: configbind.ScaffoldString, Default: "sub", Help: "profile claim that identifies a local account; sub is the provider's own identifier"},
			{Key: "oauth.admission", Kind: configbind.ScaffoldString, Default: "authenticated", Help: "authenticated, claim, registered, or existing"},
			{Key: "oauth.auto_provision", Kind: configbind.ScaffoldBool, Default: "true", Help: "permit an unknown profile to create an account through the registered account resolver"},
			{Key: "oauth.claim.path", Kind: configbind.ScaffoldString, Help: "JSON Pointer into verified claims"},
			{Key: "oauth.claim.values", Kind: configbind.ScaffoldStringSlice},
			{Key: "oauth.claim.match", Kind: configbind.ScaffoldString, Default: "any", Help: "any or all"},
			{Key: "oauth.registered_claims", Kind: configbind.ScaffoldStringSlice, Help: "claims compared against the allowlist; defaults to identity_claim"},
			{Key: "oauth.allow_loopback_http", Kind: configbind.ScaffoldBool, Default: "false", Help: "permit an http loopback redirect URL during development"},
			{Key: "passkey.path", Kind: configbind.ScaffoldString, Default: "/auth/passkey", Help: "base path of the ceremony endpoints"},
			{Key: "passkey.rp_id", Kind: configbind.ScaffoldString, Help: "relying party domain; localhost during development"},
			{Key: "passkey.rp_name", Kind: configbind.ScaffoldString, Help: "relying party display name"},
			{Key: "passkey.origins", Kind: configbind.ScaffoldStringSlice, Help: "origin the browser reaches this deployment on"},
			{Key: "passkey.user_verification", Kind: configbind.ScaffoldString, Default: "required", Help: "required, preferred, or discouraged"},
			{Key: "passkey.discoverable", Kind: configbind.ScaffoldString, Default: "preferred", Help: "required or preferred"},
			{Key: "jwt.issuer", Kind: configbind.ScaffoldString, Env: "AUTH_JWT_ISSUER", Help: "exact iss claim value this deployment accepts"},
			{Key: "jwt.audience", Kind: configbind.ScaffoldStringSlice, Help: "aud value naming this API; required"},
			{Key: "jwt.audience_match", Kind: configbind.ScaffoldString, Default: "any", Help: "any or all", Enum: []string{"any", "all"}},
			{Key: "jwt.algorithms", Kind: configbind.ScaffoldStringSlice, Help: "exact verification algorithm allowlist; required, e.g. [\"RS256\"]"},
			{Key: "jwt.required_token_type", Kind: configbind.ScaffoldString, Default: "at+jwt", Help: "typ header to demand; empty accepts an absent typ"},
			{Key: "jwt.required_scopes", Kind: configbind.ScaffoldStringSlice, Help: "scope values every request must carry"},
			{Key: "jwt.discovery", Kind: configbind.ScaffoldString, Default: "oidc", Help: "oidc, oauth, or manual", Enum: []string{"oidc", "oauth", "manual"}},
			{Key: "jwt.jwks_uri", Kind: configbind.ScaffoldString, Help: "signing key set, for manual discovery"},
			{Key: "jwt.leeway", Kind: configbind.ScaffoldDuration, Default: "30s", Help: "clock skew allowance"},
			{Key: "jwt.max_token_lifetime", Kind: configbind.ScaffoldDuration, Help: "longest exp-minus-iat accepted; required"},
			{Key: "jwt.max_token_bytes", Kind: configbind.ScaffoldInt, Default: "8192", Help: "largest compact token accepted"},
			{Key: "jwt.jwks_refresh_cooldown", Kind: configbind.ScaffoldDuration, Default: "1m", Help: "shortest interval between unknown-kid refreshes"},
			{Key: "jwt.allow_loopback_http", Kind: configbind.ScaffoldBool, Default: "false", Help: "permit an http loopback issuer during development"},
			{Key: "jwt.identity_claim", Kind: configbind.ScaffoldString, Default: "sub", Help: "verified claim that identifies a local account"},
			{Key: "jwt.admission", Kind: configbind.ScaffoldString, Help: "authenticated, claim, registered, or existing; required"},
			{Key: "jwt.auto_provision", Kind: configbind.ScaffoldBool, Default: "false", Help: "permit an unknown verified identity to create an account"},
			{Key: "jwt.claim.path", Kind: configbind.ScaffoldString, Help: "JSON Pointer into verified claims"},
			{Key: "jwt.claim.values", Kind: configbind.ScaffoldStringSlice},
			{Key: "jwt.claim.match", Kind: configbind.ScaffoldString, Default: "any", Help: "any or all"},
			{Key: "jwt.registered_claims", Kind: configbind.ScaffoldStringSlice, Help: "claims compared against the allowlist; defaults to identity_claim"},
			{Key: "jwt.revocation.mode", Kind: configbind.ScaffoldString, Help: "off, token, subject, or both; required in jwt_only"},
			{Key: "jwt.revocation.on_unavailable", Kind: configbind.ScaffoldString, Default: "refuse", Help: "refuse or admit when the store cannot answer", Enum: []string{"refuse", "admit"}},
			{Key: "jwt.revocation.max_propagation_delay", Kind: configbind.ScaffoldDuration, Help: "how stale a cached revocation answer may be; zero disables the cache"},
			{Key: "jwt.dev.trust_unverified_tokens", Kind: configbind.ScaffoldBool, Default: "false", Help: "development only: admit a token without verifying it"},
		},
	})
}

func applyConfigDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Config)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Config: bad destination")
	}
	if v, ok := o.GetString("auth.enabled"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.enabled: %w", err)
		}
		p.Enabled = bb
	} else {
		p.Enabled = false
	}
	if v, ok := o.GetString("auth.backend"); ok {
		switch v {
		case "rdb", "dynamo":
		default:
			return fmt.Errorf("configbind: auth.backend: %q must be one of: rdb, dynamo", v)
		}
		p.Backend = v
	} else {
		p.Backend = "rdb"
	}
	if v, ok := o.GetString("auth.mode"); ok {
		switch v {
		case "oidc_only", "oidc_passkey", "passkey_only", "oauth_only", "jwt_only":
		default:
			return fmt.Errorf("configbind: auth.mode: %q must be one of: oidc_only, oidc_passkey, passkey_only, oauth_only, jwt_only", v)
		}
		p.Mode = v
	} else {
		p.Mode = "oidc_only"
	}
	if v, ok := o.GetString("auth.login_path"); ok {
		p.LoginPath = v
	} else {
		p.LoginPath = "/auth/login"
	}
	if v, ok := o.GetString("auth.callback_path"); ok {
		p.CallbackPath = v
	} else {
		p.CallbackPath = "/auth/callback"
	}
	if v, ok := o.GetString("auth.logout_path"); ok {
		p.LogoutPath = v
	} else {
		p.LogoutPath = "/auth/logout"
	}
	if v, ok := o.GetString("auth.post_login_path"); ok {
		p.PostLoginPath = v
	} else {
		p.PostLoginPath = "/"
	}
	if v, ok := o.GetString("auth.recent_auth_max_age"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.recent_auth_max_age: %w", err)
		}
		p.RecentAuthMaxAge = d
	} else {
		p.RecentAuthMaxAge = 300000000000 // 5m0s
	}
	if v, ok := o.GetString("auth.shared_device"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.shared_device: %w", err)
		}
		p.SharedDevice = bb
	} else {
		p.SharedDevice = false
	}
	if ta1, ok := o.Get("auth.assurance.policy"); ok {
		if !ta1.IsTables {
			return fmt.Errorf("configbind: auth.assurance.policy: expected an array of tables ([[auth.assurance.policy]])")
		}
		p.Assurance.Policy = make([]AssurancePolicy, len(ta1.Tables))
		for i1 := range ta1.Tables {
			if v, ok := ta1.Tables[i1].GetString("name"); ok {
				p.Assurance.Policy[i1].Name = v
			}
			if v, ok := ta1.Tables[i1].GetString("max_age"); ok {
				d, err := time.ParseDuration(v)
				if err != nil {
					return fmt.Errorf("configbind: auth.assurance.policy[%d].max_age: %w", i1, err)
				}
				p.Assurance.Policy[i1].MaxAge = d
			}
			if v, ok := ta1.Tables[i1].GetString("confirm"); ok {
				bb, err := strconv.ParseBool(v)
				if err != nil {
					return fmt.Errorf("configbind: auth.assurance.policy[%d].confirm: %w", i1, err)
				}
				p.Assurance.Policy[i1].Confirm = bb
			} else {
				p.Assurance.Policy[i1].Confirm = false
			}
		}
	}
	if v, ok := o.GetString("auth.assurance.hint.enabled"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.assurance.hint.enabled: %w", err)
		}
		p.Assurance.Hint.Enabled = bb
	} else {
		p.Assurance.Hint.Enabled = false
	}
	if v, ok := o.GetString("auth.assurance.hint.name"); ok {
		p.Assurance.Hint.Name = v
	} else {
		p.Assurance.Hint.Name = "pw_hint"
	}
	if v, ok := o.GetString("auth.assurance.hint.secret"); ok {
		p.Assurance.Hint.Secret = v
	}
	if v, ok := o.GetMulti("auth.assurance.hint.previous_secrets"); ok {
		p.Assurance.Hint.PreviousSecrets = v
	}
	if v, ok := o.GetString("auth.assurance.hint.ttl"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.assurance.hint.ttl: %w", err)
		}
		p.Assurance.Hint.TTL = d
	} else {
		p.Assurance.Hint.TTL = 2592000000000000 // 720h0m0s
	}
	if v, ok := o.GetString("auth.assurance.hint.idle_timeout"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.assurance.hint.idle_timeout: %w", err)
		}
		p.Assurance.Hint.IdleTimeout = d
	} else {
		p.Assurance.Hint.IdleTimeout = 1209600000000000 // 336h0m0s
	}
	if v, ok := o.GetString("auth.assurance.presence.enabled"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.assurance.presence.enabled: %w", err)
		}
		p.Assurance.Presence.Enabled = bb
	} else {
		p.Assurance.Presence.Enabled = false
	}
	if v, ok := o.GetString("auth.assurance.presence.interval"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.assurance.presence.interval: %w", err)
		}
		p.Assurance.Presence.Interval = d
	} else {
		p.Assurance.Presence.Interval = 60000000000 // 1m0s
	}
	if v, ok := o.GetString("auth.assurance.presence.absent_after"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.assurance.presence.absent_after: %w", err)
		}
		p.Assurance.Presence.AbsentAfter = d
	} else {
		p.Assurance.Presence.AbsentAfter = 1800000000000 // 30m0s
	}
	if v, ok := o.GetMulti("auth.protection.include"); ok {
		p.Protection.Include = v
	}
	if v, ok := o.GetMulti("auth.protection.exclude"); ok {
		p.Protection.Exclude = v
	}
	if v, ok := o.GetString("auth.protection.unauthenticated"); ok {
		p.Protection.Unauthenticated = v
	} else {
		p.Protection.Unauthenticated = "redirect"
	}
	if v, ok := o.GetString("auth.registration.policy"); ok {
		p.Registration.Policy = v
	}
	if v, ok := o.GetString("auth.recovery.policy"); ok {
		p.Recovery.Policy = v
	}
	if v, ok := o.GetString("auth.bootstrap.issue_ttl"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.bootstrap.issue_ttl: %w", err)
		}
		p.Bootstrap.IssueTTL = d
	} else {
		p.Bootstrap.IssueTTL = 86400000000000 // 24h0m0s
	}
	if v, ok := o.GetString("auth.bootstrap.enrollment_ttl"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.bootstrap.enrollment_ttl: %w", err)
		}
		p.Bootstrap.EnrollmentTTL = d
	} else {
		p.Bootstrap.EnrollmentTTL = 600000000000 // 10m0s
	}
	if v, ok := o.GetString("auth.bootstrap.max_attempts"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: auth.bootstrap.max_attempts: %w", err)
		}
		p.Bootstrap.MaxAttempts = int(n)
	} else {
		p.Bootstrap.MaxAttempts = 5
	}
	if v, ok := o.GetString("auth.oidc.issuer"); ok {
		p.OIDC.Issuer = v
	}
	if v, ok := o.GetString("auth.oidc.client_id"); ok {
		p.OIDC.ClientID = v
	}
	if v, ok := o.GetString("auth.oidc.client_secret"); ok {
		p.OIDC.ClientSecret = v
	}
	if v, ok := o.GetString("auth.oidc.redirect_url"); ok {
		p.OIDC.RedirectURL = v
	}
	if v, ok := o.GetMulti("auth.oidc.scopes"); ok {
		p.OIDC.Scopes = v
	}
	if v, ok := o.GetMulti("auth.oidc.endpoint_hosts"); ok {
		p.OIDC.EndpointHosts = v
	}
	if v, ok := o.GetString("auth.oidc.identity_claim"); ok {
		p.OIDC.IdentityClaim = v
	} else {
		p.OIDC.IdentityClaim = "sub"
	}
	if v, ok := o.GetString("auth.oidc.admission"); ok {
		p.OIDC.Admission = v
	} else {
		p.OIDC.Admission = "authenticated"
	}
	if v, ok := o.GetString("auth.oidc.auto_provision"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.oidc.auto_provision: %w", err)
		}
		p.OIDC.AutoProvision = bb
	} else {
		p.OIDC.AutoProvision = true
	}
	if v, ok := o.GetString("auth.oidc.claim.path"); ok {
		p.OIDC.Claim.Path = v
	}
	if v, ok := o.GetMulti("auth.oidc.claim.values"); ok {
		p.OIDC.Claim.Values = v
	}
	if v, ok := o.GetString("auth.oidc.claim.match"); ok {
		p.OIDC.Claim.Match = v
	} else {
		p.OIDC.Claim.Match = "any"
	}
	if v, ok := o.GetMulti("auth.oidc.registered_claims"); ok {
		p.OIDC.RegisteredClaims = v
	}
	if v, ok := o.GetString("auth.oidc.logout_scope"); ok {
		switch v {
		case "reconfirm", "global":
		default:
			return fmt.Errorf("configbind: auth.oidc.logout_scope: %q must be one of: reconfirm, global", v)
		}
		p.OIDC.LogoutScope = v
	} else {
		p.OIDC.LogoutScope = "reconfirm"
	}
	if v, ok := o.GetString("auth.oidc.provider_logout"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.oidc.provider_logout: %w", err)
		}
		p.OIDC.ProviderLogout = bb
	} else {
		p.OIDC.ProviderLogout = false
	}
	if v, ok := o.GetString("auth.oidc.allow_global_logout_request"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.oidc.allow_global_logout_request: %w", err)
		}
		p.OIDC.AllowGlobalLogoutRequest = bb
	} else {
		p.OIDC.AllowGlobalLogoutRequest = false
	}
	if v, ok := o.GetString("auth.oidc.allow_loopback_http"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.oidc.allow_loopback_http: %w", err)
		}
		p.OIDC.AllowLoopbackHTTP = bb
	} else {
		p.OIDC.AllowLoopbackHTTP = false
	}
	if v, ok := o.GetString("auth.oauth.provider"); ok {
		switch v {
		case "x":
		default:
			return fmt.Errorf("configbind: auth.oauth.provider: %q must be one of: x", v)
		}
		p.OAuth.Provider = v
	}
	if v, ok := o.GetString("auth.oauth.client_id"); ok {
		p.OAuth.ClientID = v
	}
	if v, ok := o.GetString("auth.oauth.client_secret"); ok {
		p.OAuth.ClientSecret = v
	}
	if v, ok := o.GetString("auth.oauth.redirect_url"); ok {
		p.OAuth.RedirectURL = v
	}
	if v, ok := o.GetMulti("auth.oauth.scopes"); ok {
		p.OAuth.Scopes = v
	}
	if v, ok := o.GetString("auth.oauth.identity_claim"); ok {
		p.OAuth.IdentityClaim = v
	} else {
		p.OAuth.IdentityClaim = "sub"
	}
	if v, ok := o.GetString("auth.oauth.admission"); ok {
		p.OAuth.Admission = v
	} else {
		p.OAuth.Admission = "authenticated"
	}
	if v, ok := o.GetString("auth.oauth.auto_provision"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.oauth.auto_provision: %w", err)
		}
		p.OAuth.AutoProvision = bb
	} else {
		p.OAuth.AutoProvision = true
	}
	if v, ok := o.GetString("auth.oauth.claim.path"); ok {
		p.OAuth.Claim.Path = v
	}
	if v, ok := o.GetMulti("auth.oauth.claim.values"); ok {
		p.OAuth.Claim.Values = v
	}
	if v, ok := o.GetString("auth.oauth.claim.match"); ok {
		p.OAuth.Claim.Match = v
	} else {
		p.OAuth.Claim.Match = "any"
	}
	if v, ok := o.GetMulti("auth.oauth.registered_claims"); ok {
		p.OAuth.RegisteredClaims = v
	}
	if v, ok := o.GetString("auth.oauth.allow_loopback_http"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.oauth.allow_loopback_http: %w", err)
		}
		p.OAuth.AllowLoopbackHTTP = bb
	} else {
		p.OAuth.AllowLoopbackHTTP = false
	}
	if v, ok := o.GetString("auth.passkey.path"); ok {
		p.Passkey.Path = v
	} else {
		p.Passkey.Path = "/auth/passkey"
	}
	if v, ok := o.GetString("auth.passkey.rp_id"); ok {
		p.Passkey.RPID = v
	}
	if v, ok := o.GetString("auth.passkey.rp_name"); ok {
		p.Passkey.RPName = v
	}
	if v, ok := o.GetMulti("auth.passkey.origins"); ok {
		p.Passkey.Origins = v
	}
	if v, ok := o.GetString("auth.passkey.user_verification"); ok {
		p.Passkey.UserVerification = v
	} else {
		p.Passkey.UserVerification = "required"
	}
	if v, ok := o.GetString("auth.passkey.discoverable"); ok {
		p.Passkey.Discoverable = v
	} else {
		p.Passkey.Discoverable = "preferred"
	}
	if v, ok := o.GetString("auth.jwt.issuer"); ok {
		p.JWT.Issuer = v
	}
	if v, ok := o.GetMulti("auth.jwt.audience"); ok {
		p.JWT.Audience = v
	}
	if v, ok := o.GetString("auth.jwt.audience_match"); ok {
		switch v {
		case "any", "all":
		default:
			return fmt.Errorf("configbind: auth.jwt.audience_match: %q must be one of: any, all", v)
		}
		p.JWT.AudienceMatch = v
	} else {
		p.JWT.AudienceMatch = "any"
	}
	if v, ok := o.GetMulti("auth.jwt.algorithms"); ok {
		p.JWT.Algorithms = v
	}
	if v, ok := o.GetString("auth.jwt.required_token_type"); ok {
		p.JWT.RequiredTokenType = v
	} else {
		p.JWT.RequiredTokenType = "at+jwt"
	}
	if v, ok := o.GetMulti("auth.jwt.required_scopes"); ok {
		p.JWT.RequiredScopes = v
	}
	if v, ok := o.GetString("auth.jwt.discovery"); ok {
		switch v {
		case "oidc", "oauth", "manual":
		default:
			return fmt.Errorf("configbind: auth.jwt.discovery: %q must be one of: oidc, oauth, manual", v)
		}
		p.JWT.Discovery = v
	} else {
		p.JWT.Discovery = "oidc"
	}
	if v, ok := o.GetString("auth.jwt.jwks_uri"); ok {
		p.JWT.JWKSURI = v
	}
	if v, ok := o.GetString("auth.jwt.leeway"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.jwt.leeway: %w", err)
		}
		p.JWT.Leeway = d
	} else {
		p.JWT.Leeway = 30000000000 // 30s
	}
	if v, ok := o.GetString("auth.jwt.max_token_lifetime"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.jwt.max_token_lifetime: %w", err)
		}
		p.JWT.MaxTokenLifetime = d
	}
	if v, ok := o.GetString("auth.jwt.max_token_bytes"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: auth.jwt.max_token_bytes: %w", err)
		}
		p.JWT.MaxTokenBytes = int(n)
	} else {
		p.JWT.MaxTokenBytes = 8192
	}
	if v, ok := o.GetString("auth.jwt.jwks_refresh_cooldown"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.jwt.jwks_refresh_cooldown: %w", err)
		}
		p.JWT.JWKSRefreshCooldown = d
	} else {
		p.JWT.JWKSRefreshCooldown = 60000000000 // 1m0s
	}
	if v, ok := o.GetString("auth.jwt.allow_loopback_http"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.jwt.allow_loopback_http: %w", err)
		}
		p.JWT.AllowLoopbackHTTP = bb
	} else {
		p.JWT.AllowLoopbackHTTP = false
	}
	if v, ok := o.GetString("auth.jwt.identity_claim"); ok {
		p.JWT.IdentityClaim = v
	} else {
		p.JWT.IdentityClaim = "sub"
	}
	if v, ok := o.GetString("auth.jwt.admission"); ok {
		p.JWT.Admission = v
	}
	if v, ok := o.GetString("auth.jwt.auto_provision"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.jwt.auto_provision: %w", err)
		}
		p.JWT.AutoProvision = bb
	} else {
		p.JWT.AutoProvision = false
	}
	if v, ok := o.GetString("auth.jwt.claim.path"); ok {
		p.JWT.Claim.Path = v
	}
	if v, ok := o.GetMulti("auth.jwt.claim.values"); ok {
		p.JWT.Claim.Values = v
	}
	if v, ok := o.GetString("auth.jwt.claim.match"); ok {
		p.JWT.Claim.Match = v
	} else {
		p.JWT.Claim.Match = "any"
	}
	if v, ok := o.GetMulti("auth.jwt.registered_claims"); ok {
		p.JWT.RegisteredClaims = v
	}
	if v, ok := o.GetString("auth.jwt.revocation.mode"); ok {
		p.JWT.Revocation.Mode = v
	}
	if v, ok := o.GetString("auth.jwt.revocation.on_unavailable"); ok {
		switch v {
		case "refuse", "admit":
		default:
			return fmt.Errorf("configbind: auth.jwt.revocation.on_unavailable: %q must be one of: refuse, admit", v)
		}
		p.JWT.Revocation.OnUnavailable = v
	} else {
		p.JWT.Revocation.OnUnavailable = "refuse"
	}
	if v, ok := o.GetString("auth.jwt.revocation.max_propagation_delay"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.jwt.revocation.max_propagation_delay: %w", err)
		}
		p.JWT.Revocation.MaxPropagationDelay = d
	}
	if v, ok := o.GetString("auth.jwt.dev.trust_unverified_tokens"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.jwt.dev.trust_unverified_tokens: %w", err)
		}
		p.JWT.Dev.TrustUnverifiedTokens = bb
	} else {
		p.JWT.Dev.TrustUnverifiedTokens = false
	}
	return nil
}

func registerSessionLifetimeConfigDefinition1() {
	configbind.Register[SessionLifetimeConfig](configbind.Definition{
		TypeName: "github.com/shibukawa/popcornweb/plugin/auth.SessionLifetimeConfig",
		Prefix:   "auth.session",
		Doc:      "SessionLifetimeConfig is the [auth.session] binding, declared in popcornweb/sessionconfig so that pw can read it without importing this package",
		KnownKeys: []string{
			"auth.session.ttl",
			"auth.session.idle_timeout",
			"auth.session.renewal_interval",
		},
		Defaults: map[string]string{
			"auth.session.ttl":              "24h",
			"auth.session.idle_timeout":     "0s",
			"auth.session.renewal_interval": "0s",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "auth.session", Key: "ttl", Help: "absolute session lifetime"},
			{Prefix: "auth.session", Key: "idle_timeout", Help: "inactivity expiry; zero disables it"},
			{Prefix: "auth.session", Key: "renewal_interval", Help: "minimum interval between idle expiry renewals"},
		},
		Apply: applySessionLifetimeConfigDefinition1,
		Scaffold: []configbind.ScaffoldField{
			{Key: "ttl", Kind: configbind.ScaffoldDuration, Default: "24h", Help: "absolute session lifetime"},
			{Key: "idle_timeout", Kind: configbind.ScaffoldDuration, Default: "0s", Help: "inactivity expiry; zero disables it"},
			{Key: "renewal_interval", Kind: configbind.ScaffoldDuration, Default: "0s", Help: "minimum interval between idle expiry renewals"},
		},
	})
}

func applySessionLifetimeConfigDefinition1(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*SessionLifetimeConfig)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply SessionLifetimeConfig: bad destination")
	}
	if v, ok := o.GetString("auth.session.ttl"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.session.ttl: %w", err)
		}
		p.TTL = d
	} else {
		p.TTL = 86400000000000 // 24h0m0s
	}
	if v, ok := o.GetString("auth.session.idle_timeout"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.session.idle_timeout: %w", err)
		}
		p.IdleTimeout = d
	} else {
		p.IdleTimeout = 0 // 0s
	}
	if v, ok := o.GetString("auth.session.renewal_interval"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.session.renewal_interval: %w", err)
		}
		p.RenewalInterval = d
	} else {
		p.RenewalInterval = 0 // 0s
	}
	return nil
}
